# BUILD 
FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . . 

# PRODUCTION
FROM node:20-alpine AS production
WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

COPY --from=builder /app ./

ENV NODE_ENV=production

EXPOSE 3000
CMD [ "node", "server.js" ]