name: ACR test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to ACR
        run: |
          docker login ${{  secrets.ACR_URL  }} -u ${{  secrets.ACR_USERNAME  }} -p ${{ secrets.ACR_PASSWORD }}

      - name: Build & test API
        run: |
          docker build -t ${{  secrets.ACR_URL  }}/api:latest ./api
          docker run --rm ${{  secrets.ACR_URL  }}/api:latest npm test

      - name: Push image to ACR
        run: |
          docker push ${{  secrets.ACR_URL  }}/api:latest
