name: Frontend CI

on:
  push:
    branches:
      - main
      - feature/*

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # API
      - name: Build API image
        working-directory: api
        run: |
          docker build -t ${{  secrets.ACR_URL  }}/api:latest ./api
          docker run --rm ${{  secrets.ACR_URL  }}/api:latest npm test

      - name: Login to ACR
        run: |
          docker login ${{  secrets.ACR_URL  }} -u ${{  secrets.ACR_USERNAME  }} -p ${{ secrets.ACR_PASSWORD }}

      - name: Push API image to ACR
        run: |
          docker push ${{  secrets.ACR_URL  }}/api:latest

      # FRONTEND
      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Run lint
        working-directory: frontend
        run: npm run lint

      - name: Run tests
        working-directory: frontend
        run: npm test

      - name: Build frontend runtime image
        working-directory: frontend
        run: |
          docker build --target runtime -t ${{ secrets.ACR_URL }}/frontend:latest ./frontend

      - name: Push frontend image to ACR
        run: |
          docker push ${{ secrets.ACR_URL }}/frontend:latest

      - name: Build project
        if: github.ref == 'refs/heads/main'
        working-directory: frontend
        run: npm run build

      - name: Mock deploy
        if: github.ref == 'refs/heads/main'
        run: echo "mock deploy done (y)"
