name: Dev CI (build → test → deploy)

on:
  push:
    branches:
      - dev

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Init CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3

      - name: Log in to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_URL }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build API image
        run: |
          docker build -t ${{ secrets.ACR_URL }}/api:${{ github.sha }} ./api

      - name: Run API tests
        run: docker run --rm ${{ secrets.ACR_URL }}/api:${{ github.sha }} npm test

      - name: Push API image to ACR
        run: |
          docker push ${{ secrets.ACR_URL }}/api:${{ github.sha }}

      - name: Deploy to Azure Web App (DEV  )
        uses: azure/webapps-deploy@v2
        with:
          app-name: "antona-webapp"
          images: "${{ secrets.ACR_URL }}/api:${{ github.sha }}"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
