name: info

on:
  push:
    branches:
      - main

jobs:
  info-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: print info
        run: echo "commit hash ${{ github.sha }} branch ${{ github.ref }}"
